### ISSUE TITLE
Backend Service not responding

### ISSUE THREAD

**Issue by whittlem** [ionutbv16/react-hooks-redux-toast-api#6]
As per the README.md I cloned the repo, ran yarn and yarn start. The app loads fine but when I submit the Todo it says "Backend Service not responding". What is is trying to communicate with?

**Comment by whittlem** [comment]
I do see one warning:

Compiled with warnings.

./src/containers/Todos.tsx
  Line 36:  React Hook useEffect has a missing dependency: 'dispatch'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

**Comment by ionutbv16** [comment]
This repository should be installed, this is backend service https://github.com/ionutbv16/node-express-mongoose

**Comment by whittlem** [comment]
That worked, thanks.
